package com.hamdy.showtime.ui.util

const val API_KEY="400225a1886f38d9cf3c934d6a756c4d"
const val YouTubeBase="https://www.youtube.com/watch?v="
const val ImageUrlBase = "http://image.tmdb.org/t/p/w500/"
const val SUCCESSFUL_RESPONSE_VALUE = "Successful"
const val FAILED_RESPONSE_VALUE = "Failed"
const val SHARED_PREF_ID = "ShowTimeAuth"
const val LOGIN_KEY = "login"
const val ID_KEY = "id"
const val POSTER_PATH_KEY = "posterPath"
const val TYPE_KEY = "type"
const val UPCOMING_KEY = "upComing"
const val TOP_RATE_KEY = "topRate"
const val POPULAR_KEY = "popular"
const val USERS_KEY = "Users"
const val TRAILER_KEY = "Trailer"
const val FAVORITE_MOVIES_KEY = "FavoriteMovies"
const val FAVORITE_ID_KEY = "favoriteId"
const val POSTER_KEY = "poster"
const val IMDB_ID_KEY = "imdb_id"
const val FAVORITE_PERSONS_KEY = "FavoritePersons"
const val FAVORITE_BACK_KEY = "favoriteBack"
const val USERNAME_KEY = "userName"
const val USER_ID_KEY = "userId"
const val PERSONS_KEY = "Persons"
const val MOVIES_KEY = "Movies"